services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu-mco
    ports:
      - "3307:3306"
    networks:
      - sgu-net
    volumes:
      - sgu-volume:/var/lib/mysql
  frontend:
    image: client:1.0-sgu
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8082
        API_BASE: /api
        API_PROTOCOL: https
        
    container_name: sgu-frontend
    ports:
      - "3000:443"
    networks:
      - sgu-net
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - database
  backend:
    image: server:1.0-sgu
    build:
      context: ./server
    container_name: sgu-backend
    environment:  
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: sgu-mco
      SERVER_PORT: 8080
      SERVER_SSL_ENABLED: true
      SERVER_SSL_KEYSTORE: /etc/letsencrypt/live/localhost/keystore.p12
      SERVER_SSL_PASS: changeit  
    ports:
      - "8082:8080"
    networks:
      - sgu-net
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - frontend
#docker network create --driver bridge sgu-net
networks:
  sgu-net:
    external: true

# docker volume create sgu-volume
volumes:
  sgu-volume:
    external: true
  certbot-conf:
    external: true
#docker compose up -d --build

#docker compose down -v