services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu-mco
    ports:
      - "3307:3306"
    networks:
      - sgu-net
    volumes:
      - sgu-volume:/var/lib/mysql
  frontend:
    image: client:v1.0
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8082
        API_BASE: /api
    container_name: sgu-client
    ports:
      - "3000:80"
    networks:
      - sgu-net
    depends_on:
      - database
  backend:
    image: server:v1.0
    build:
      context: ./server
    container_name: sgu-server  
    environment:  
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: sgu-mco
      SERVER_PORT: 8080   
    ports:
      - "8082:8080"
    networks:
      - sgu-net
    depends_on:
      - frontend
#docker network create --driver bridge sgu-net
networks:
  sgu-net:
    external: true

# docker volume create sgu-volume
volumes:
  sgu-volume:
    external: true

#docker compose up -d --build

#docker compose down -v